blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://iroiro.dev/Neumorphism/documentation/neumorphism/
    about: More information on using Neumorphism can be found here.
